export { Agent, AgentBuilder } from "./agent/index.js";
export type { AgentConfig, AgentOptions, AgentTool, RunOptions, RunResult } from "./agent/index.js";
export type {
  ApprovalContext,
  ApprovalDecision,
  ApprovalManagerConfig,
  ApprovalPolicy,
  ApprovalProvider,
  ApprovalRequest,
  ApprovalResponse,
  ApprovalResult,
  HumanApproval,
} from "./approval/index.js";
export {
  AlwaysApprovePolicy,
  ApprovalDecisionStatus,
  ApprovalManager,
  ApprovalRegistry,
  CompositeApprovalPolicy,
  LocalApprovalProvider,
  NeverApprovePolicy,
  SensitiveToolApprovalPolicy,
} from "./approval/index.js";
export {
  ApprovalRejectedError,
  ApprovalError,
  ConfigurationError,
  GuardrailViolationError,
  HandoffError,
  MemoryError,
  MiddlewareError,
  PluginError,
  ProviderError,
  RuntimeError,
  SessionError,
  ShiroError,
  ShiroErrorCode,
  TimeoutError,
  ToolExecutionError,
  ToolNotFoundError,
  ValidationError,
} from "./errors/index.js";
export { Engine, EngineState, PipelineStage, Runner, RunnerState } from "./engine/index.js";
export type {
  AgentProviderResolver,
  EngineConfig,
  EngineContextFactory,
  EngineServices,
  EngineSnapshot,
  PipelineResult,
  RunInput,
  RunnerDependencies,
  RunnerOptions,
  RunnerSnapshot,
} from "./engine/index.js";
export type { ShiroErrorDetails } from "./errors/index.js";
export { ShiroEventType } from "./events/index.js";
export type {
  AgentStartedEvent,
  AgentHandoffCompletedEvent,
  AgentHandoffFailedEvent,
  AgentHandoffRequestedEvent,
  AgentHandoffStartedEvent,
  AgentRegisteredEvent,
  AgentResolvedEvent,
  ApprovalGrantedEvent,
  ApprovalCancelledEvent,
  ApprovalRejectedEvent,
  ApprovalRequestedEvent,
  ApprovalTimedOutEvent,
  BaseShiroEvent,
  Disposable,
  EventBus,
  EventByType,
  EventHandler,
  GuardrailCheckedEvent,
  GuardrailViolatedEvent,
  HandoffCompletedEvent,
  HandoffRequestedEvent,
  MemoryReadEvent,
  ContextPreparedEvent,
  MemoryCompactedEvent,
  MemoryRetrievedEvent,
  MemoryStoredEvent,
  MemoryUpdatedEvent,
  OutputRepairCompletedEvent,
  OutputRepairFailedEvent,
  OutputRepairStartedEvent,
  OutputValidationFailedEvent,
  OutputValidationStartedEvent,
  OutputValidationSucceededEvent,
  ProviderFinishedEvent,
  ProviderStartedEvent,
  RunCompletedEvent,
  RunFailedEvent,
  RunStartedEvent,
  SpanCompletedEvent,
  SpanStartedEvent,
  ShiroEvent,
  SessionCreatedEvent,
  SessionLoadedEvent,
  SessionUpdatedEvent,
  ToolFinishedEvent,
  ToolCompletedEvent,
  ToolFailedEvent,
  ToolRequestedEvent,
  ToolStartedEvent,
  ToolTimedOutEvent,
  TraceCompletedEvent,
  TraceExportedEvent,
  TraceStartedEvent,
  TraceUpdatedEvent,
} from "./events/index.js";
export { GuardrailDecision, GuardrailStage } from "./guardrails/index.js";
export type { Guardrail, GuardrailContext, GuardrailResult } from "./guardrails/index.js";
export {
  AgentExecutionGraph,
  AgentRegistry,
  HandoffDecisionStatus,
  HandoffDepthLimiter,
  HandoffManager,
  HandoffStrategyType,
  SequentialHandoffStrategy,
} from "./handoff/index.js";
export type {
  AgentResolver,
  HandoffContext,
  HandoffDecision,
  HandoffResult,
  HandoffStrategy,
} from "./handoff/index.js";
export {
  DefaultContextCompactor,
  DefaultMemoryRetrievalStrategy,
  InMemoryMemoryProvider,
  MemoryManager,
} from "./memory/index.js";
export type {
  ContextCompactionOptions,
  ContextCompactor,
  ConversationContext,
  MemoryEntry,
  MemoryProvider,
  MemoryReadContext,
  MemoryRecord,
  MemoryRetrievalStrategy,
  MemorySearchQuery,
  MemorySnapshot,
  MemoryWriteContext,
} from "./memory/index.js";
export type { Middleware, MiddlewareContext, MiddlewareRunResult } from "./middleware/index.js";
export {
  DefaultOutputRepairStrategy,
  JsonOutputParser,
  SchemaOutputValidator,
  StructuredOutputManager,
} from "./output/index.js";
export type {
  InferOutput,
  OutputParser,
  OutputRepairRequest,
  OutputRepairStrategy,
  OutputSchema,
  OutputValidationContext,
  OutputValidator,
  RetryPolicy,
  SafeParseResult,
  StructuredOutputEvents,
  StructuredOutputManagerConfig,
  StructuredOutputRequest,
  StructuredOutputResult,
  ValidationIssue,
  ValidationResult,
} from "./output/index.js";
export {
  DefaultPluginContext,
  PluginCapability,
  PluginLifecycle,
  PluginManager,
  PluginRegistry,
} from "./plugin/index.js";
export type {
  Plugin,
  PluginCapabilityDefinition,
  PluginContext,
  PluginContributions,
  PluginDependency,
  PluginEventListener,
  PluginLoader,
  PluginManagerConfig,
  PluginMetadata,
  PluginSnapshot,
  StudioExtension,
} from "./plugin/index.js";
export {
  BaseProvider,
  ProviderRegistry,
  RegistryProviderResolver,
  toProviderError,
} from "./provider/index.js";
export type {
  Provider,
  ProviderCapabilities,
  ProviderContext,
  ProviderFactory,
  ProviderFactoryConfig,
  ProviderMetadata,
  ProviderRequest,
  ProviderResolver,
  ProviderResponse,
} from "./provider/index.js";
export type { EngineContext, RunContext, RuntimeContext } from "./runtime/index.js";
export { createSessionSnapshot, InMemorySessionStore, SessionManager } from "./session/index.js";
export type {
  ConversationState,
  Session,
  SessionExecutionStats,
  SessionSnapshot,
  SessionStore,
} from "./session/index.js";
export { FinishReason, MessageRole } from "./shared/index.js";
export type {
  CancellationOptions,
  JsonArray,
  JsonObject,
  JsonPrimitive,
  JsonValue,
  Message,
  Metadata,
  ResourceId,
  TimeoutOptions,
} from "./shared/index.js";
export {
  tool,
  ToolExecutionState,
  ToolExecutor,
  ToolRegistry,
  ToolSerializer,
  validateTool,
  validateToolArguments,
} from "./tool/index.js";
export type {
  Tool,
  ToolCall,
  ToolCallRequest,
  ToolCallResult,
  ToolContext,
  ToolDefinition,
  ToolExecutionOptions,
  ToolLogger,
  ToolResult,
  ToolSchema,
} from "./tool/index.js";
export {
  ConsoleTraceExporter,
  InMemoryTraceStore,
  JsonTraceExporter,
  TraceManager,
  TraceSpanCategory,
  TraceSpanStatus,
  TraceStatus,
} from "./tracing/index.js";
export type {
  ApprovalTrace,
  HandoffTrace,
  MemoryTrace,
  ModelCallTrace,
  RunTrace,
  TokenUsage,
  ToolExecutionTrace,
  TraceAttributes,
  TraceEvent,
  TraceExporter,
  TraceFilter,
  TraceManagerConfig,
  TraceSnapshot,
  TraceSpan,
  TraceSpanHandle,
  TraceStatistics,
  TraceStore,
  TraceTimeline,
  Tracer,
} from "./tracing/index.js";
